// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRbA_eCQoxzqDJDJOxnT_g8fVUPYuMmM',
    appId: '1:853472397092:web:ccf67962591e1f6c4c55b1',
    messagingSenderId: '853472397092',
    projectId: 'campus-7b240',
    authDomain: 'campus-7b240.firebaseapp.com',
    storageBucket: 'campus-7b240.firebasestorage.app',
    measurementId: 'G-5ZSKCND26H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKirV3pXIrtROb52yhYI_irLcskuBpcY',
    appId: '1:853472397092:android:df6de778727abc7d4c55b1',
    messagingSenderId: '853472397092',
    projectId: 'campus-7b240',
    storageBucket: 'campus-7b240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHGVjFCeT3dJNRt2HZANG9H-mJnXeMos',
    appId: '1:853472397092:ios:e74bff44a612a2944c55b1',
    messagingSenderId: '853472397092',
    projectId: 'campus-7b240',
    storageBucket: 'campus-7b240.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

}